swagger: "2.0"
info:
  title: IPFS over HTTP
  description: An API to add json objects to the local IPFS node
  version: 1.0.0

host: ipfs.nikeshnazareth.com:3000
schemes:
  - http

paths: 'api/add-path.yaml'