swagger: "2.0"
info:
  title: Seed API
  description: The API for the Express Seed project
  version: 1.0.0

host: localhost:3000
schemes:
  - http

paths:
  /dummy:
    get:
      summary: Gets a dummy response object
      description: The response is the object `{dummyResponse: 'Dum de dum dum'}` (wrapped in a `data` field)
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Unexpected server error