swagger: "2.0"
info:
  title: IPFS over HTTPS
  description: An API to add json objects to the local IPFS node
  version: 1.0.0

host: ipfs.nikeshnazareth.com
schemes:
  - https

paths: 'api/add-path.yaml'